### ISSUE TITLE
Little error

### ISSUE THREAD

**Issue by seisdr** [Thunder07/ps4-pup-unpacker#3]
```
[ 85%] Building CXX object CMakeFiles/pup_unpacker.dir/PUP.cpp.o
In file included from /data/data/com.termux/files/home/ps4-pup-unpacker/PUP.cpp:2:
In file included from /data/data/com.termux/files/home/ps4-pup-unpacker/zstr.hpp:16:
/data/data/com.termux/files/home/ps4-pup-unpacker/extern/zstr/src/strict_fstream.hpp:39:36: error:
      cannot initialize a parameter of type 'const char *' with an lvalue of type 'int'
    std::string tmp(p, std::strlen(p));
                                   ^
/data/data/com.termux/files/usr/include/string.h:95:27: note: passing argument to parameter '__s'
      here
size_t strlen(const char* __s) __attribute_pure__;
                          ^
1 error generated.
make[2]: *** [CMakeFiles/pup_unpacker.dir/build.make:76: CMakeFiles/pup_unpacker.dir/PUP.cpp.o] Error 1
```

**Comment by XapaJIaMnu** [comment]
Doesn't compile on mac. This should be fixed in master, but in case someone googles it for another tool that uses zstr on mac, the solution is here: https://github.com/Zer0xFF/zstr/blob/14e3b27d6fb8581925aeced66b564ab6b8a6fec0/src/strict_fstream.hpp#L30

**Comment by Zer0xFF** [comment]
thanks @XapaJIaMnu for replying to this, as noted, this is fixed, not sure why you'd get this, since i believe this repo, was always directed to my repo with the fix.

going to close this, if this is still an issue, the please feel free to open it again

**Comment by XapaJIaMnu** [comment]
I posted this here, because googling this error results in two hits and no solutions. I was porting another library to mac and spent 20 minutes on this.
